# Default values for saleor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
deploymentName: saleor-allinone
container:
  saleor_dashboard:
    name: saleor-platform-dashboard
    image: 254126128186.dkr.ecr.us-east-1.amazonaws.com/saleor-platform_dashboard:latest
    port: 9000
  saleor_worker:
    name: saleor-platform-worker
    image: 254126128186.dkr.ecr.us-east-1.amazonaws.com/saleor-platform_worker:latest
    #    port: 8080
  saleor_api:
    name: saleor-platform-api
    image: 254126128186.dkr.ecr.us-east-1.amazonaws.com/saleor-platform_api:latest
    port: 8000
  saleor_storefront:
    name: saleor-platform-storefront
    image: 254126128186.dkr.ecr.us-east-1.amazonaws.com/saleor-platform_storefront:latest
    port: 3000
  saleor_postgress:
    name: saleor-postgress
    image: 254126128186.dkr.ecr.us-east-1.amazonaws.com/postgres:latest
    port: 5432
  redis:
    name: saleor-redis
    image: 254126128186.dkr.ecr.us-east-1.amazonaws.com/redis:latest
    port: 6379
  saleor_pla:
    name: saleor-pla
    image: 254126128186.dkr.ecr.us-east-1.amazonaws.com/jaegertracing/all-in-one:latest
    port: 16686
