apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deploymentName }}
spec:
  selector:
    app: {{ .Values.deploymentName }}
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: {{ .Values.container.saleor_dashboard.name }}
      port: 80
      targetPort: {{ .Values.container.saleor_dashboard.port }}
    - protocol: TCP
      name: {{ .Values.container.saleor_storefront.name }}
      port: 81
      targetPort: {{ .Values.container.saleor_storefront.port }}